[package]
name = "simple_stdio"
version = "0.1.0"
edition = "2024"

[dependencies]
gpmcp-layer = { path = "../../crates/gpmcp-layer" }
tokio = { version = "1.45.1", features = ["macros"] }
anyhow = "1.0.98"
